
<section class="start-page parallax-background" id="home">
  
    <div class="opacity"></div>
      <div class="content"  style="align: left;">
        <div class="text">
        
          <h1>Welcome<br/>
          to <span>DOCPro</span></h1>
          <p>Accounting and Bookkeeping System</p>
        </div>
      </div>

  <!-- section menu mobile -->
  
  <section class="menu-media">
  
    <div class="menu-content">
    
      <div class="logo">DOCPro System</div>
      
      <div class="icon"><a href="#"><img src="<?php echo base_url(); ?>libs/onepage/HTML/img/icons/menu-media.png"/></a></div>
    
    </div>

  </section>
  
    <ul class="menu-click">
        <a href="<?php echo base_url(); ?>"><li>Home</li></a>
        <a href="<?php echo base_url(); ?>"><li>Subscription</li></a>
        <a href="<?php echo base_url(); ?>"><li>About</li></a>
        <a href="<?php echo base_url(); ?>"><li>Gallery</li></a>
        <a href="<?php echo base_url(); ?>"><li>Contact</li></a>
        <a href="<?php echo base_url(); ?>login"><li>Sign in</li></a>
    </ul>
   
  <!-- section menu -->

  <section class="menu">

    <div class="menu-content">
    
    <div class="logo">
      <span>
        <img src="<?php echo base_url(); ?>assets/img/85x85.png">
      </span>
      <span id="company_name">
       <img src="<?php echo base_url(); ?>assets/img/logo-text.png">
      </span>
    </div>
    
      <ul id="menu">
        <li><a href="<?php echo base_url(); ?>">Home</a></li>
        <li class='active'><a href="<?php echo base_url(); ?>">Subscription</a></li>
        <li><a href="<?php echo base_url(); ?>">Features</a></li>
        <li><a href="<?php echo base_url(); ?>">Gallery</a></li>
        <li><a href="<?php echo base_url(); ?>">Contact</a></li>
        <li><a href="<?php echo base_url(); ?>login">Sign in</a></li>
      </ul>
    </div>
  
  </section>

  <div class='container' id="free-container" style="width: 100%;">
    <div class="row" style="opacity: 1; margin-left: 25px; margin-bottom: 25px;"> <!-- Row 1 -->
      <h1 style="padding-left: 20px;
                 padding-top: 20px;">
        Reports
        </h1>
      <div class="col-md-4" style="padding-left: 25px;">
        <div class="panel">
          <div class="panel-heading">
            <h3 style="padding-top: 10px; text-align: left;">Simple Summary</h3>
          </div>
          <div class="panel-body" style="text-align: left;">
            <p>
              Always know at a glance just how much is outstanding and if you have any overdue invoices.
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-4" style="padding-left: 25px;">
        <div class="panel">
          <div class="panel-heading">
            <h3 style="padding-top: 10px; text-align: left;">Financial Reporting</h3>
          </div>
          <div class="panel-body" style="text-align: left;">
            <p>
              View and share interactive reports and budget in real time - no more waiting for month end.
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-4" style="padding-left: 25px;">
        <div class="panel">
          <div class="panel-heading">
            <h3 style="padding-top: 10px; text-align: left;">Business Performance Dashboard </h3>
          </div>
          <div class="panel-body" style="text-align: left;">
            <p>
              Quickly see how your business is performing with different performance metrics.
            </p>
          </div>
        </div>
      </div>

    </div> <!-- end div of Row 1 -->

    
    <div class="row" style="opacity: 1; margin-left: 25px; margin-bottom: 25px;"> <!-- 	Row 2 -->
      <div class="col-md-4" style="padding-left: 25px;">
        <div class="panel">
          <div class="panel-heading">
            <h3 style="padding-top: 10px; text-align: left;">Accountant Friendly Reports</h3>
          </div>
          <div class="panel-body" style="text-align: left;">
            <p>
              Working with an accountant, reports generated by docpro are simple and easy to understand by your accountant.
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-4" style="padding-left: 25px;">
        <div class="panel">
          <div class="panel-heading">
            <h3 style="padding-top: 10px; text-align: left;">Expense Report</h3>
          </div>
          <div class="panel-body" style="text-align: left;">
            <p>
              Keep your spending in check with the expense report. Get a detailed breakdown of where you've spend your money in any given time frame.
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-4" style="padding-left: 25px;">
        <div class="panel">
          <div class="panel-heading">
            <h3 style="padding-top: 10px; text-align: left;">Search</h3>
          </div>
          <div class="panel-body" style="text-align: left;">
            <p>
              Search across all of your transactions to find <br />
              the information you're looking for.
            </p>
          </div>
        </div>
      </div>

    </div> <!-- end div of Row 2 -->    

    <!-- Footer section -->
  
  <footer class="footer" id="free-footer">
    <div class="margin">
      <div class="menu-footer">
        <a href="#home">Home</a>
        <a href="#">FAQ</a>
        <a href="<?php echo base_url(); ?>privacy_policy">Privacy policy</a>
        <a href="#">Terms & Condition</a>
      </div>
      <div class="copyright">&copy; 2016. All Rights Reserved DocPro Business Solution</div>        
    </div>
  </footer>
  </div>


  

  




